name: Mobile Automation Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Android SDK Command-Line Tools
        run: |
          mkdir -p "$ANDROID_HOME/cmdline-tools"
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-mac-8512546_latest.zip
          unzip sdk-tools.zip -d "$ANDROID_HOME/cmdline-tools"
          mv "$ANDROID_HOME/cmdline-tools/cmdline-tools" "$ANDROID_HOME/cmdline-tools/latest"
          yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --licenses
        env:
          ANDROID_HOME: $HOME/Library/Android/sdk
          PATH: $PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools

      - name: Install Required System Image
        run: |
          sdkmanager --install "system-images;android-35;google_apis_playstore;x86_64"
        env:
          ANDROID_HOME: $HOME/Library/Android/sdk
          PATH: $PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools

      - name: Launch Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          target: google_apis_playstore
          arch: x86_64
          profile: pixel_3a
          emulator-options: -no-boot-anim -gpu swiftshader -verbose
          cores: 2
          avd-name: test
          force-avd-creation: true
          emulator-boot-timeout: 1200
          emulator-port: 5554
          disable-animations: true
          disable-linux-hw-accel: true
          enable-hw-keyboard: true
          channel: stable
          script: |
            adb devices # List connected devices
            adb shell input keyevent 82 # Unlock the emulator screen

      - name: Wait for Emulator
        run: adb wait-for-device && adb shell input keyevent 82

      - name: Cache Maven Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Install Maven Dependencies
        run: mvn clean install

      - name: Start Appium Server
        run: |
          appium --log-level debug --address 127.0.0.1 --port 4723 &
        shell: bash

      - name: Run Tests
        run: mvn test -Dplatform=android
